# Based on <https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/wezterm/Pro.toml>

[colors]
foreground = "#f2f2f2"
background = "#000000"
cursor_bg = "#9a9a9a"
cursor_border = "#4d4d4d"
cursor_fg = "#ffffff"
selection_bg = "#414141"
selection_fg = "#000000"

scrollbar_thumb = "#cccccc"

ansi = [
    "#000000",  # Black
    "#990000",  # Red
    "#00a600",  # Green
    "#999900",  # Yellow
    "#5455cb",  # Blue
    "#b200b2",  # Magenta
    "#00a6b2",  # Cyan
    "#bfbfbf",  # White
]

brights = [
    "#666666",  # Bright black
    "#e50000",  # Bright red
    "#00d900",  # Bright green
    "#e5e500",  # Bright yellow
    "#5555ff",  # Bright blue
    "#e500e5",  # Bright magenta
    "#00e5e5",  # Bright cyan
    "#e5e5e5",  # Bright white
]
