config:
  backup: true
  banner: false
  create: true
  dotpath: files
  filter_file:
    - lib/filters.py
  force_chmod: true
  ignoreempty: true
  keepdot: true
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
  showdiff: true
  template_dotfile_default: false

actions:
  post:
    private-dir: 'chmod 0700 {{@@ dirname(_dotfile_abs_dst) @@}}'

dynvariables:
  lesspath: command -v less
  vimpath: command -v vim

dotfiles:
  f_bash_completion:
    src: .bash_completion
    dst: ~/.bash_completion
  f_bashrc:
    src: .bashrc
    dst: ~/.bashrc
    template: true
  f_cargo_config_toml:
    src: .cargo/config.toml
    dst: ~/.cargo/config.toml
  f_config_pip_pip.conf:
    src: .config/pip/pip.conf
    dst: ~/.config/pip/pip.conf
  f_config_rgignore:
    src: .config/rgignore
    dst: ~/.config/rgignore
  f_config_ripgrep.rc:
    src: .config/ripgrep.rc
    dst: ~/.config/ripgrep.rc
    template: true
  f_config_wezterm_wezterm.lua:
    src: .config/wezterm/wezterm.lua
    dst: ~/.config/wezterm/wezterm.lua
  f_dircolors:
    src: .dircolors
    dst: ~/.dircolors
  f_gitconfig:
    src: .gitconfig
    dst: ~/.gitconfig
  f_gnupg_gpg.conf:
    src: .gnupg/gpg.conf
    dst: ~/.gnupg/gpg.conf
    chmod: '600'
    actions:
      - private-dir
  f_inputrc:
    src: .inputrc
    dst: ~/.inputrc
  f_jq:
    src: .jq
    dst: ~/.jq
  f_mutt_colors:
    src: .mutt/colors
    dst: ~/.mutt/colors
  f_mutt_gpg:
    src: .mutt/gpg
    dst: ~/.mutt/gpg
  f_mutt_keys:
    src: .mutt/keys
    dst: ~/.mutt/keys
  f_mutt_local:
    src: .mutt/local
    dst: ~/.mutt/local
    template: true
  f_mutt_muttrc:
    src: .mutt/muttrc
    dst: ~/.mutt/muttrc
    template: true
  f_profile:
    src: .profile
    dst: ~/.profile
    template: true
  f_screenrc:
    src: .screenrc
    dst: ~/.screenrc
  f_tmux_conf:
    src: .tmux.conf
    dst: ~/.tmux.conf
  d_vim:
    src: .vim
    dst: ~/.vim
    cmpignore:
      - .netrwhist
      - autoload
      - plugged
      - '!spell/words.utf-8.add'
      - 'spell/[a-zA-Z0-9]*'
  f_bin_apt-check:
    src: bin/apt-check
    dst: ~/bin/apt-check
    chmod: '0755'
  f_bin_apt-purge:
    src: bin/apt-purge
    dst: ~/bin/apt-purge
    chmod: '0755'
  f_bin_apt-upgrade:
    src: bin/apt-upgrade
    dst: ~/bin/apt-upgrade
    chmod: '0755'
  f_bin_cargo-coverage:
    src: bin/cargo-coverage
    dst: ~/bin/cargo-coverage
    chmod: '0755'
  f_bin_cargo-docsrs:
    src: bin/cargo-docsrs
    dst: ~/bin/cargo-docsrs
    chmod: '0755'
  f_bin_cargo-updeps:
    src: bin/cargo-updeps
    dst: ~/bin/cargo-updeps
    chmod: '0755'
  f_bin_clear:
    src: bin/clear
    dst: ~/bin/clear
    chmod: '0755'
  f_bin_email:
    src: bin/email
    dst: ~/bin/email
    chmod: '0755'
  f_bin_git-branch-log:
    src: bin/git-branch-log
    dst: ~/bin/git-branch-log
    chmod: '0755'
  f_bin_git-branch-range:
    src: bin/git-branch-range
    dst: ~/bin/git-branch-range
    chmod: '0755'
  f_bin_git-default-branch:
    src: bin/git-default-branch
    dst: ~/bin/git-default-branch
    chmod: '0755'
  f_bin_git-fork-point:
    src: bin/git-fork-point
    dst: ~/bin/git-fork-point
    chmod: '0755'
  f_bin_git-newbranch:
    src: bin/git-newbranch
    dst: ~/bin/git-newbranch
    chmod: '0755'
  f_bin_git-post-merge:
    src: bin/git-post-merge
    dst: ~/bin/git-post-merge
    chmod: '0755'
  f_bin_git-restore-head:
    src: bin/git-restore-head
    dst: ~/bin/git-restore-head
    chmod: '0755'
  f_bin_git-restore-index:
    src: bin/git-restore-index
    dst: ~/bin/git-restore-index
    chmod: '0755'
  f_bin_git-rmbranch:
    src: bin/git-rmbranch
    dst: ~/bin/git-rmbranch
    chmod: '0755'
  f_bin_git-update:
    src: bin/git-update
    dst: ~/bin/git-update
    chmod: '0755'
  f_bin_pim:
    src: bin/pim
    dst: ~/bin/pim
    chmod: '0755'
  f_bin_pygrep:
    src: bin/pygrep
    dst: ~/bin/pygrep
    chmod: '0755'
  f_bin_with-tab-title:
    src: bin/with-tab-title
    dst: ~/bin/with-tab-title
    chmod: '0755'
  f_share_project-as-title.py:
    src: share/project-as-title.py
    dst: ~/share/project-as-title.py
    chmod: '0755'
  f_share_pylinting.cfg:
    src: share/pylinting.cfg
    dst: ~/share/pylinting.cfg
  f_share_util.gbc:
    src: share/util.gbc
    dst: ~/share/util.gbc

profiles:
  base:
    dotfiles:
      - f_bash_completion
      - f_bashrc
      - f_bin_cargo-coverage
      - f_bin_cargo-docsrs
      - f_bin_cargo-updeps
      - f_bin_git-branch-log
      - f_bin_git-branch-range
      - f_bin_git-default-branch
      - f_bin_git-fork-point
      - f_bin_git-newbranch
      - f_bin_git-post-merge
      - f_bin_git-restore-head
      - f_bin_git-restore-index
      - f_bin_git-rmbranch
      - f_bin_git-update
      - f_bin_pim
      - f_bin_pygrep
      - f_cargo_config_toml
      - f_config_pip_pip.conf
      - f_config_rgignore
      - f_config_ripgrep.rc
      - f_gitconfig
      - f_gnupg_gpg.conf
      - f_inputrc
      - f_jq
      - f_profile
      - f_screenrc
      - f_tmux_conf
      - d_vim
      - f_share_project-as-title.py
      - f_share_pylinting.cfg
      - f_share_util.gbc

  macOS:
    include:
      - base
    dotfiles:
      - f_config_wezterm_wezterm.lua
      - f_bin_clear
      - f_bin_with-tab-title

  debian:
    include:
      - base
    dotfiles:
      - f_bin_apt-check
      - f_bin_apt-purge
      - f_bin_apt-upgrade
      - f_dircolors

  debian-mail:
    include:
      - debian
    dotfiles:
      - f_bin_email
      - f_mutt_colors
      - f_mutt_gpg
      - f_mutt_keys
      - f_mutt_local
      - f_mutt_muttrc
