[alias]
clap = ["add", "clap", "--no-default-features", "--features", "derive,error-context,help,std,suggestions,usage,wrap_help"]
lint = ["clippy", "--all-features", "--all-targets", "--", "-Dwarnings"]
