#!/bin/bash
set -eux -o pipefail

function have_command {
    command -V "$1" >/dev/null 2>&1
}

if ! have_command pipx
then
    if have_command brew
    then brew install pipx
    elif have_command apt-get && sudo -n true 2>/dev/null
    then sudo apt-get install -y pipx
    elif have_command pacman && sudo -n true 2>/dev/null
    then sudo pacman -S --noconfirm pipx
    else printf '\x1B[31m[ERROR] pipx is not installed.\x1B[m\n' >&2
         exit 1
    fi
fi

pipx install black
pipx install build
pipx install coverage   # Needed for the Vim coverage plugin
pipx install flake8
pipx inject flake8 flake8-bugbear flake8-builtins flake8-unused-arguments
pipx install isort
pipx install jwodder-ps1
pipx install mypy
pipx install pre-commit
pipx install tox
pipx install virtualenvwrapper
