#!/bin/bash
set -ex -o pipefail

#if ! pipx list --json | jq -e '.venvs | has("datalad")' > /dev/null
if ! pipx list | grep -q dotdrop
then pipx install dotdrop
fi

"$(dirname "$0")"/../dotdrop.sh install --nodiff --force

mkdir -p ~/work
[ ! -d ~/.mutt ] || mkdir -p ~/Mail
