#!/bin/bash
set -ex -o pipefail

mkdir -p ~/.vim/pack/plugins/start
cd ~/.vim/pack/plugins/start
for repo in https://github.com/cespare/vim-toml \
            https://github.com/knatsakis/deb.vim \
            https://github.com/ntpeters/vim-better-whitespace
do [ -e "$(basename "$repo")" ] || git clone "$repo"
done
